name: Build Chilagu APK RAHISI

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Toa code
        uses: actions/checkout@v4
        
      - name: Weka Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Weka Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          
      - name: Fungua zip yako
        run: |
          unzip "zip Chilagu Cinema.zip" -d .
          rm "zip Chilagu Cinema.zip"
          
      - name: Pakua packages
        run: flutter pub get
        
      - name: Jenga APK
        run: flutter build apk --debug
        
      - name: Panda APK hapa
        uses: actions/upload-artifact@v4
        with:
          name: APK-RAHISI
          path: build/app/outputs/flutter-apk/app-debug.apk
